"""secure user mobile fields

Revision ID: 1082c226ba58
Revises: 393b6ccaa1f3
Create Date: 2026-08-23 21:05:35.890570

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1082c226ba58'
down_revision: Union[str, Sequence[str], None] = '393b6ccaa1f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('mobile_encrypted', sa.String(length=512), nullable=True))
    op.add_column('users', sa.Column('mobile_hash', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_users_mobile_hash'), 'users', ['mobile_hash'], unique=True)
    op.drop_column('users', 'mobile')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('mobile', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_users_mobile_hash'), table_name='users')
    op.drop_column('users', 'mobile_hash')
    op.drop_column('users', 'mobile_encrypted')
    # ### end Alembic commands ###
